
trigger: none

pool: infra-pool

steps:  
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'narayanServiceConnection'
    backendAzureRmStorageAccountName: 'test'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'




